ff2:
  flow_matcher:
    flow_trans: True
    flow_rot: True
    ot_fn: exact
    reg: 0.05 # only used if ot_fn is 'sinkhorn'.
    ot_plan: False # Using OT plan to pair the noise with data. Default False.
    stochastic_paths: False # Switches to stochastic

    # R(3) Flow Matcher arguments
    r3:
      min_b: 0.01
      min_sigma: 0.01
      max_b: 20.0
      coordinate_scaling: 0.1
      g: 0.1

    # SO(3) Flow Matcher arguments
    so3:
      min_sigma: 0.01
      max_sigma: 1.5
      axis_angle: True
      inference_scaling: -0.01
      g: 0.1

  model:
    model_name: "ff2"
    esm2_model_key: "esm2_650M" # Trained with "esm2_650M"  esm2_35M_270K
    scaffold_training: False
    binder_training: False
    binder_percent_fix_structure: 1.0
    bb_encoder:
      num_blocks: 2
      coordinate_scaling: ${ff2.flow_matcher.r3.coordinate_scaling}
    bb_decoder:
      num_blocks: 2
      coordinate_scaling: ${ff2.flow_matcher.r3.coordinate_scaling}
    seq_emb_to_block:
      single_dim: 128
      pair_dim: 128
    representation_combiner:
      single_dim: 128 # NOTE: If proj+concat, the total dim will be 512
      pair_dim: 64 # NOTE: If proj+concat, the total dim will be 512
      layer_norm: True
    modalities_transformer:
      trunk_type: "transformer"
      num_blocks: 2
      sequence_head_width: 32
      pairwise_head_width: 32
      chunk_size: null # null won't chunk. Lower chunk_size reduce memory, but reduces speed.
    p_mask_sequence: 0.5

    embed:
      embed_self_conditioning: True
      use_alphafold_position_embedding: False
      relpos_k: 32