model:
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: False
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    max_num_res: 2000
    timestep_int: 1000
    embed_chain: False
  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    feat_dim: 64
    num_bins: 22
    self_condition: True
    embed_chain: False
    embed_diffuse_mask: True
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 16
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6
  Hourglass:
    dim: ${model.node_embed_size}
    depth: [ 2, 2]
    shorten_factor: [1,1]
    downproj_factor: [1,1]
    attn_resampling: true
    updown_sample_type: 'linear'
    heads: 8
    dim_head: 64
    causal: false
    norm_out: false
    n_e: 512
    e_dim: 64
  sh:
    hidden_scalar: ${model.node_embed_size}
    C: 4
    L_max: 8
    R_bins: 24
    L_edge: 2
    n_layers: 12
    n_radial: 8
    dropout: 0.1
    k_neighbors: 24
    num_classes: 20
    r_max: 8
    voxel_size: 0.25
    min_peak_distance: 0.8
    topk_per_channel: [10, 4, 3, 1]
  FA:
    d_model: ${model.node_embed_size}
    n_heads: 24
    num_layers: 12


